"""Synthetic recovery demonstration for competing nectar-guide scenarios.

Run:
    python examples/synthetic_scenario_recovery.py

It first supplies only a broad total-contribution interval, then adds visit and
outcross-seed observations generated by a known visit-attraction scenario.
The point is to show that the added intermediate measures, not a hidden model
label, drive recovery.
"""

from channel_id.guide_inbreeding import PostSeedSurvival
from channel_id.guide_paternal import PaternalGuideParameters
from channel_id.guide_scenarios import (
    GuideScenario,
    ScenarioMetric,
    ScenarioObservation,
    ScenarioSettings,
    ScenarioYear,
    recover_compatible_scenarios,
    simulate_guide_scenario,
)
from channel_id.guide_spatial import Patch
from channel_id.nectar_guide import NectarGuideParameters, NectarGuideTrait


settings = ScenarioSettings(
    trait=NectarGuideTrait(guide_contrast=0.8, display=0.4, assurance=0.5),
    maternal_parameters=NectarGuideParameters(
        seed_budget=10.0,
        display_cost=0.0,
        guide_cost=0.0,
        assurance_cost=0.1,
        baseline_visit_rate=0.2,
        display_visit_gain=0.0,
        guide_visit_gain=1.0,
        baseline_legitimate_fraction=0.2,
        guide_handling_gain=0.8,
        pollen_to_outcross_fraction=1.0,
        selfing_viability=0.6,
        baseline_establishment=1.0,
    ),
    paternal_parameters=PaternalGuideParameters(
        baseline_pollen_export=1.0,
        display_export_gain=0.0,
        guide_export_gain=1.0,
        baseline_siring_success=0.2,
    ),
    post_seed_survival=PostSeedSurvival(0.4, 0.5),
    years=(ScenarioYear("typical", 0.7),),
    spatial_patches=(Patch("occupied", 0.8, 100.0),),
    spatial_dispersal=(1.0,),
)

truth = simulate_guide_scenario(GuideScenario.VISIT_ATTRACTION, settings)
total = truth.metric(ScenarioMetric.TOTAL_CONTRIBUTION, "typical")
visits = truth.metric(ScenarioMetric.EXPECTED_VISITS, "typical")
outcross = truth.metric(ScenarioMetric.OUTCROSS_VIABLE_SEEDS, "typical")

coarse = recover_compatible_scenarios(
    tuple(GuideScenario),
    settings,
    (ScenarioObservation(ScenarioMetric.TOTAL_CONTRIBUTION, total - 3.0, total + 3.0, "typical"),),
)
resolved = recover_compatible_scenarios(
    tuple(GuideScenario),
    settings,
    (
        ScenarioObservation(ScenarioMetric.EXPECTED_VISITS, visits - 1e-8, visits + 1e-8, "typical"),
        ScenarioObservation(ScenarioMetric.OUTCROSS_VIABLE_SEEDS, outcross - 1e-8, outcross + 1e-8, "typical"),
    ),
)

print("Coarse total-contribution observation retains:", [report.scenario.value for report in coarse])
print("After visit + outcross-seed observations:", [report.scenario.value for report in resolved])
